USE Project390DB;

INSERT INTO DailyQuote (quote, date) VALUES
('The only way to do great work is to love what you do.', '2025-05-01'),
('Success is not final, failure is not fatal: It is the courage to continue that counts.', '2025-05-02'),
('Believe you can and you’re halfway there.', '2025-05-03'),
('Act as if what you do makes a difference. It does.', '2025-05-04'),
('Success usually comes to those who are too busy to be looking for it.', '2025-05-05'),
('Don’t watch the clock; do what it does. Keep going.', '2025-05-06'),
('The harder you work for something, the greater you’ll feel when you achieve it.', '2025-05-07'),
('Dream big and dare to fail.', '2025-05-08'),
('Don’t be afraid to give up the good to go for the great.', '2025-05-09'),
('It always seems impossible until it’s done.', '2025-05-10'),
('Opportunities don''t happen, you create them.', '2025-05-11'),
('Do not wait to strike till the iron is hot, but make it hot by striking.', '2025-05-12'),
('Everything you can imagine is real.', '2025-05-13'),
('What we think, we become.', '2025-05-14'),
('The future belongs to those who believe in the beauty of their dreams.', '2025-05-15'),
('Success is not how high you have climbed, but how you make a positive difference to the world.', '2025-05-16'),
('If you want to lift yourself up, lift up someone else.', '2025-05-17'),
('You are never too old to set another goal or to dream a new dream.', '2025-05-18'),
('It does not matter how slowly you go as long as you do not stop.', '2025-05-19'),
('The only limit to our realization of tomorrow is our doubts of today.', '2025-05-20'),
('What lies behind us and what lies before us are tiny matters compared to what lies within us.', '2025-05-21'),
('Everything you’ve ever wanted is on the other side of fear.', '2025-05-22'),
('The best way to predict the future is to create it.', '2025-05-23'),
('Believe in yourself and all that you are. Know that there is something inside you that is greater than any obstacle.', '2025-05-24'),
('To be yourself in a world that is constantly trying to make you something else is the greatest accomplishment.', '2025-05-25'),
('The only way to achieve the impossible is to believe it is possible.', '2025-05-26'),
('Life is 10% what happens to us and 90% how we react to it.', '2025-05-27'),
('Do what you can with all you have, wherever you are.', '2025-05-28'),
('You miss 100% of the shots you don’t take.', '2025-05-29'),
('Keep your face always toward the sunshine—and shadows will fall behind you.', '2025-05-30'),
('It’s not whether you get knocked down, it’s whether you get up.', '2025-05-31');
